# Generated by Django 5.2.5 on 2025-08-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_membershiptypebyadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='membership_since',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
