# Generated by Django 5.2.5 on 2025-08-27 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_membership_since'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='membership_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TUCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Standing Committee Member', 'Standing Committee Member'), ('Executive Committee Member', 'Executive Committee Member'), ('Head of the Inspection Committee', 'Head of the Inspection Committee'), ('Member of the Inspection Committee', 'Member of the Inspection Committee'), ('Trade Union Accountant', 'Trade Union Accountant'), ('Trade Union Treasurer', 'Trade Union Treasurer')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('responsible_floor', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('9', '9'), ('10', '10'), ('11', '11'), ('Hanoi', 'Hanoi'), ('Club Administrator', 'Club Administrator'), ('Overall', 'Overall')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tu_committees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
