# Generated by Django 5.2.5 on 2025-09-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_tupotexporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday_gift_received',
            field=models.BooleanField(default=False, help_text='Had received birthday gift for the current year'),
        ),
    ]
