# Generated by Django 5.2.5 on 2025-09-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_birthday_gift_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tet_gift_received',
            field=models.BooleanField(default=False, help_text='Had received Tet gift for the current year'),
        ),
    ]
