# Generated by Django 5.2.5 on 2025-09-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_tet_gift_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mooncake_gift_received',
            field=models.BooleanField(default=False, help_text='Had received Moon Cake gift for the current year'),
        ),
    ]
