# Generated by Django 5.2.5 on 2025-09-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_mooncake_gift_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='luckymoney_gift_received',
            field=models.BooleanField(default=False, help_text='Had received Lucky Money gift for the current year'),
        ),
    ]
