# Generated by Django 5.2.5 on 2025-09-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_luckymoney_gift_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='june_gift_received',
            field=models.BooleanField(default=False, help_text='Received June Children gift for the current year'),
        ),
    ]
