# Generated by Django 5.2.5 on 2025-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_children_june_gift_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='autumn_gift_received',
            field=models.BooleanField(default=False, help_text='Received Autumn Children gift for the current year'),
        ),
    ]
