# Generated by Django 5.2.5 on 2025-09-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_children_autumn_gift_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGiftYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gift_type', models.CharField(max_length=50)),
                ('received', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'year', 'gift_type')},
            },
        ),
    ]
