# Generated by Django 5.2.5 on 2025-09-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeegiftyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Thu'), ('expense', 'Chi')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTemplateDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_type', models.CharField(choices=[('income', 'Thu'), ('expense', 'Chi')], max_length=10)),
                ('date', models.DateField()),
                ('document', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.financialcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('template_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.financialtemplatedescription')),
            ],
        ),
    ]
