# Generated by Django 5.2.5 on 2025-09-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_financialcategory_financialtemplatedescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialtransaction',
            old_name='document',
            new_name='payment_id',
        ),
    ]
