# Generated by Django 5.2.5 on 2025-09-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_rename_document_financialtransaction_payment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialTemplateDescription',
            new_name='FinancialDescription',
        ),
        migrations.RenameField(
            model_name='financialtransaction',
            old_name='template_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='payment_evidence',
            field=models.ImageField(blank=True, null=True, upload_to='financial_evidence/'),
        ),
    ]
