# Generated by Django 5.2.5 on 2025-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_rename_financialtemplatedescription_financialdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdescription',
            name='type',
            field=models.CharField(choices=[('income', 'Thu'), ('expense', 'Chi')], default='income', max_length=10),
        ),
    ]
