# Generated by Django 5.2.5 on 2025-09-09 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_financialdescription_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialTransaction',
            new_name='TUFinancialTransaction',
        ),
        migrations.AlterField(
            model_name='financialdescription',
            name='type',
            field=models.CharField(choices=[('income', 'Thu'), ('expense', 'Chi')], max_length=10),
        ),
        migrations.CreateModel(
            name='ClubFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ClubFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('payment_id', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('financial_type', models.CharField(choices=[('income', 'Thu'), ('expense', 'Chi')], max_length=10)),
                ('payment_evidence', models.ImageField(blank=True, null=True, upload_to='financial_evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.financialcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.financialdescription')),
            ],
        ),
        migrations.CreateModel(
            name='FloorFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.floor')),
            ],
        ),
        migrations.CreateModel(
            name='FloorFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_id', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('financial_type', models.CharField(choices=[('income', 'Thu'), ('expense', 'Chi')], max_length=10)),
                ('payment_evidence', models.ImageField(blank=True, null=True, upload_to='financial_evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.financialcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.financialdescription')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.floor')),
            ],
        ),
        migrations.CreateModel(
            name='TUFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tu', 'TU'), ('floor', 'Floor'), ('club', 'Club')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
            options={
                'unique_together': {('type', 'year', 'month')},
            },
        ),
    ]
