# Generated by Django 5.2.5 on 2025-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_rename_financialtransaction_tufinancialtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcategory',
            name='estimated_expense',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated expense/income for this category', max_digits=15),
        ),
    ]
