# Generated by Django 5.2.5 on 2025-09-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_financialcategory_estimated_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdescription',
            name='category',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='employee.financialcategory'),
        ),
    ]
