# Generated by Django 5.2.5 on 2025-09-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_financialdescription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdescription',
            name='estimated_expense',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated budget for this description', max_digits=15),
        ),
    ]
