# Generated by Django 5.2.5 on 2025-09-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_financialdescription_estimated_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdescription',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='employee.financialcategory'),
        ),
    ]
