# Generated by Django 5.2.5 on 2025-09-14 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_financialdescription_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clubfinancialtransaction',
            name='club_name',
        ),
        migrations.AddField(
            model_name='clubfinancialtransaction',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employee.club'),
            preserve_default=False,
        ),
    ]
