# Generated by Django 5.2.5 on 2025-09-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_club_remove_clubfinancialtransaction_club_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcategory',
            name='for_type',
            field=models.CharField(choices=[('tu', 'TU'), ('club', 'Club'), ('both', 'Both')], default='tu', max_length=10),
        ),
    ]
